import type { Metadata } from 'next';
import '../globals.css';
import AppLayout from '@/components/layout/app-layout';
import { Inter } from 'next/font/google';
import { getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';
import SessionProvider from '@/providers/SessionProvider';
import { getServerSession } from 'next-auth';

const fonts = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Spotting money',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();
  const session = await getServerSession();
  return (
    <html lang={locale}>
      <body className={`${fonts.className} antialiased`}>
        <SessionProvider session={session}>
          <NextIntlClientProvider messages={messages}>
            <AppLayout>{children}</AppLayout>
          </NextIntlClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
